server:
  port: 8888
  servlet:
    context-path: /UNIME

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/unimehospital"
    username: root
    password: 2706phuongnhung
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

#    open-in-view: false
jwt:
  signerKey: "4UXF7e8ExKlokbDG0p+/6ICPRLVRVt/GTksOF/+8p5vD+BiPaoKAJJbwmoywIcbv"